name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make libgtest-dev build-essential

    # Step 3: Build Google Test from source
    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo mv lib/libgtest.a lib/libgtest_main.a /usr/lib/

    # Step 4: Build the project
    - name: Build project
      run: make

    # Step 5: Run tests
    - name: Run tests
      run: ./test